-- 진단용 쿼리: 로컬(lib/seedData.ts) 기준 139건 slug 목록과
-- 현재 Supabase benefits 테이블을 비교해, 어떤 항목이 누락됐는지 확인합니다.
-- 결과로 나오는 slug들이 Supabase에 아직 들어가지 않은 항목입니다.

with expected(slug) as (
  values
  ('anyang-birth-grant'),
  ('anyang-youth-certification-fee-support'),
  ('anyang-youth-rent-support'),
  ('bucheon-newlywed-rent-interest-support'),
  ('bucheon-youth-photo-support'),
  ('bucheon-youth-rent-interest-support'),
  ('busan-maternal-newborn-care'),
  ('busan-newlywed-housing-loan-interest'),
  ('busan-youth-didimdol-card'),
  ('busan-youth-rent-support'),
  ('changwon-birth-celebration-grant'),
  ('changwon-newlywed-jeonse-interest-support'),
  ('changwon-youth-rent-support'),
  ('changwon-youth-savings-account'),
  ('cheongju-birth-household-loan-interest-support'),
  ('cheongju-marriage-cost-loan-interest-support'),
  ('cheongju-newlywed-housing-loan-interest-support'),
  ('chuncheon-birth-celebration-grant'),
  ('chungbuk-childcare-birthday-allowance'),
  ('chungbuk-newlywed-birth-loan-interest-support'),
  ('chungbuk-youth-rent-support'),
  ('chungnam-boryeong-marriage-grant'),
  ('chungnam-cheonan-birth-celebration-grant'),
  ('chungnam-youth-rent-support'),
  ('chungnam-youth-settlement-plus-account'),
  ('daegu-birth-celebration-grant'),
  ('daegu-newlywed-jeonse-loan-interest'),
  ('daegu-youth-hope-savings'),
  ('daegu-youth-rent-support'),
  ('daejeon-childcare-basic-allowance'),
  ('daejeon-newlywed-jeonse-loan-interest'),
  ('daejeon-youth-challenge-support'),
  ('daejeon-youth-rent-support'),
  ('gangnam-youth-rent-support'),
  ('gangwon-basic-childcare-allowance'),
  ('gangwon-newlywed-jeonse-interest-support'),
  ('gangwon-youth-job-prep-coupon'),
  ('gangwon-youth-rent-support'),
  ('gimhae-birth-celebration-grant'),
  ('gimhae-newlywed-jeonse-interest-support'),
  ('gimhae-youth-rent-support'),
  ('goyang-birth-grant'),
  ('goyang-birth-household-rent-interest-support'),
  ('goyang-youth-nest-loan'),
  ('goyang-youth-startup-support'),
  ('gumi-birth-celebration-grant'),
  ('gumi-marriage-encouragement-grant'),
  ('gumi-youth-package-support'),
  ('gumi-youth-rent-support'),
  ('gwangju-igiwoom-birth-grant'),
  ('gwangju-newlywed-jeonse-loan-interest'),
  ('gwangju-youth-job-seeking-allowance'),
  ('gwangju-youth-rent-support'),
  ('gyeongbuk-newlywed-deposit-interest-support'),
  ('gyeongbuk-youth-love-dream-allowance'),
  ('gyeongbuk-youth-rent-support'),
  ('gyeonggi-basic-income-youth'),
  ('gyeonggi-basic-income-youth-2022'),
  ('gyeonggi-basic-income-youth-2023'),
  ('gyeonggi-basic-income-youth-2024'),
  ('gyeonggi-basic-income-youth-2025'),
  ('gyeonggi-jeonse-guarantee-fee-support'),
  ('gyeonggi-newlywed-jeonse-loan-interest'),
  ('gyeonggi-postpartum-care-support'),
  ('gyeongju-birth-grant'),
  ('gyeongju-youth-home-purchase-interest-support'),
  ('gyeongnam-moda-dream-youth-account'),
  ('gyeongnam-newlywed-birth-home-purchase-interest-support'),
  ('gyeongnam-youth-rent-support'),
  ('hwaseong-birth-grant'),
  ('hwaseong-marriage-savings-match'),
  ('hwaseong-youth-certification-fee-support'),
  ('hwaseong-youth-rent-support'),
  ('incheon-dream-check-card'),
  ('incheon-jeonse-guarantee-fee-support'),
  ('incheon-newlywed-jeonse-loan-interest'),
  ('incheon-postpartum-care-support'),
  ('incheon-postpartum-care-support-2025'),
  ('jeju-childcare-support-grant'),
  ('jeju-newlywed-birth-jeonse-interest-support'),
  ('jeju-youth-hope-charge-rent-support'),
  ('jeju-youth-hope-ladder-savings'),
  ('jeonbuk-newlywed-jeonse-interest-support'),
  ('jeonbuk-youth-rent-support'),
  ('jeonbuk-youth-vitality-allowance'),
  ('jeonju-birth-celebration-grant'),
  ('jeonju-newlywed-wedding-cost-support'),
  ('jeonju-youth-one-won-housing'),
  ('jeonju-youth-rent-support'),
  ('jeonnam-childcare-welfare-allowance'),
  ('jeonnam-marriage-celebration-grant'),
  ('jeonnam-youth-culture-welfare-card'),
  ('jeonnam-youth-welfare-rent-support'),
  ('jinju-birth-celebration-grant'),
  ('jinju-newlywed-home-purchase-interest-support'),
  ('jinju-youth-certification-fee-support'),
  ('jinju-youth-rent-support'),
  ('mokpo-newlywed-multichild-housing-support'),
  ('mokpo-youth-asset-building-account'),
  ('mokpo-youth-worker-housing-support'),
  ('pohang-birth-grant'),
  ('pohang-newlywed-rent-support'),
  ('pohang-youth-challenge-support'),
  ('pohang-youth-rent-support'),
  ('sejong-birth-celebration-grant'),
  ('sejong-newlywed-jeonse-interest-support'),
  ('sejong-youth-hope-savings'),
  ('sejong-youth-rent-subsidy'),
  ('seongnam-birth-celebration-grant'),
  ('seongnam-unemployed-youth-support'),
  ('seongnam-youth-rent-moving-support'),
  ('seoul-maternal-newborn-care'),
  ('seoul-newlywed-loan-interest'),
  ('seoul-newlywed-loan-interest-2022'),
  ('seoul-newlywed-loan-interest-2023'),
  ('seoul-newlywed-loan-interest-2024'),
  ('seoul-newlywed-loan-interest-2025'),
  ('seoul-newlywed-wedding-cost-support'),
  ('seoul-youth-allowance'),
  ('seoul-youth-rent-support'),
  ('seoul-youth-rent-support-2022'),
  ('seoul-youth-rent-support-2023'),
  ('seoul-youth-rent-support-2024'),
  ('seoul-youth-rent-support-2025'),
  ('suncheon-birth-grant'),
  ('suncheon-newlywed-jeonse-interest-support'),
  ('suncheon-youth-activity-points'),
  ('suncheon-youth-worker-housing-support'),
  ('suwon-youth-housing-package'),
  ('ulsan-junggu-newlywed-jeonse-interest-support'),
  ('ulsan-ulju-birth-grant'),
  ('ulsan-youth-allowance'),
  ('ulsan-youth-rent-support'),
  ('wonju-birth-local-produce-support'),
  ('yeosu-pregnancy-celebration-grant'),
  ('yongin-birth-pregnancy-support-grant'),
  ('yongin-newlywed-jeonse-interest-support'),
  ('yongin-youth-certification-fee-support'),
  ('yongin-youth-rent-deposit-interest-support')
)
select expected.slug
from expected
left join benefits b on b.slug = expected.slug
where b.slug is null
order by expected.slug;

-- 참고용: 카테고리별 현재 Supabase 게시 건수 (is_published = true 기준)
select c.slug as category, count(*) as published_count
from benefits b
join categories c on c.id = b.category_id
where b.is_published = true
group by c.slug
order by c.slug;
