import { Benefit, Category, Region } from "./types";

/**
 * Supabase가 아직 연결되지 않았을 때 사용하는 로컬 예시 데이터입니다.
 * 내용은 supabase/seed.sql과 동일한 예시이며, 실제 서비스 데이터가 아닙니다.
 * Supabase 연결 후에는 이 파일 대신 DB의 값이 사용됩니다.
 */

export const seedRegions: Region[] = [
  { id: "r-seoul", slug: "seoul", name: "서울특별시", level: "sido", parent_id: null },
  { id: "r-gyeonggi", slug: "gyeonggi", name: "경기도", level: "sido", parent_id: null },
  { id: "r-incheon", slug: "incheon", name: "인천광역시", level: "sido", parent_id: null },
  { id: "r-seoul-gangnam", slug: "seoul-gangnam", name: "강남구", level: "sigungu", parent_id: "r-seoul" },
  { id: "r-seoul-mapo", slug: "seoul-mapo", name: "마포구", level: "sigungu", parent_id: "r-seoul" },
  { id: "r-gyeonggi-suwon", slug: "gyeonggi-suwon", name: "수원시", level: "sigungu", parent_id: "r-gyeonggi" },
];

export const seedCategories: Category[] = [
  { id: "c-marriage", slug: "marriage", name: "결혼", description: "결혼 준비·신혼부부를 위한 지원 제도", sort_order: 1 },
  { id: "c-birth", slug: "birth", name: "출산·육아", description: "임신, 출산, 양육과 관련된 지원 제도", sort_order: 2 },
  { id: "c-youth", slug: "youth", name: "청년", description: "청년(만 19~39세 내외) 대상 지원 제도", sort_order: 3 },
  { id: "c-housing", slug: "housing", name: "주거", description: "전월세, 주택 구입 관련 지원 제도", sort_order: 4 },
];

export const seedBenefits: Benefit[] = [
  {
    id: "b-seoul-youth-rent-support",
    slug: "seoul-youth-rent-support",
    title: "서울시 청년 월세 지원 (예시)",
    summary: "서울에 거주하는 무주택 청년의 월세 부담을 줄여주기 위한 지원 제도입니다.",
    region_id: "r-seoul",
    category_id: "c-housing",
    eligibility: "서울시에 주민등록이 되어 있고, 부모와 별도로 거주하는 만 19~39세 무주택 청년이면 신청할 수 있습니다.",
    support_content: "월 최대 20만원, 최장 12개월까지 월세를 지원합니다. (예시 금액이며 실제 공고 기준 확인 필요)",
    application_method: "서울주거포털 또는 정부24에서 온라인으로 신청합니다. 접수 기간 중에만 신청이 가능합니다.",
    required_documents: ["임대차계약서", "주민등록등본", "통장 사본", "소득 증빙 서류"],
    checklist: [
      "본인 명의 임대차계약서인지 확인하세요",
      "부모와 세대가 분리되어 있는지 확인하세요",
      "기존에 다른 주거 지원을 받고 있지 않은지 확인하세요",
    ],
    faq: [
      {
        question: "재학생도 신청할 수 있나요?",
        answer: "재학 여부와 관계없이 연령·거주 요건을 충족하면 신청할 수 있는 경우가 많습니다. 공고문에서 정확한 기준을 확인하세요.",
      },
    ],
    agency_name: "서울시 청년정책담당관",
    agency_url: null,
    income_condition: "기준 중위소득 150% 이하 (예시)",
    age_min: 19,
    age_max: 39,
    household_type: "1인가구",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "예시 데이터",
    source_updated_at: null,
    is_published: true,
  },
  {
    id: "b-seoul-newlywed-loan-interest",
    slug: "seoul-newlywed-loan-interest",
    title: "서울시 신혼부부 전세자금 대출이자 지원 (예시)",
    summary: "전세자금 대출을 받은 서울 거주 신혼부부에게 이자의 일부를 지원합니다.",
    region_id: "r-seoul",
    category_id: "c-marriage",
    eligibility: "혼인신고 후 7년 이내이거나 3개월 내 결혼 예정인 부부로, 서울시에 거주(예정)해야 합니다.",
    support_content: "대출금 최대 2억원에 대해 연 최대 3.0%p 이내로 이자를 지원합니다. (예시 수치)",
    application_method: "서울주거포털에서 온라인 신청 후 서류 심사를 거칩니다.",
    required_documents: ["혼인관계증명서", "전세임대차계약서", "대출 관련 서류", "소득 증빙 서류"],
    checklist: ["부부합산 소득 기준을 충족하는지 확인하세요", "보증금 및 대출한도 기준을 확인하세요"],
    faq: [],
    agency_name: "서울시 주택정책과",
    agency_url: null,
    income_condition: "부부합산 연소득 1억 3천만원 이하 (예시)",
    age_min: null,
    age_max: null,
    household_type: "신혼부부",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "예시 데이터",
    source_updated_at: null,
    is_published: true,
  },
  {
    id: "b-gyeonggi-basic-income-youth",
    slug: "gyeonggi-basic-income-youth",
    title: "경기도 청년 기본소득 (예시)",
    summary: "경기도에 일정 기간 거주한 청년에게 분기별 지역화폐를 지급합니다.",
    region_id: "r-gyeonggi",
    category_id: "c-youth",
    eligibility: "신청일 기준 경기도에 3년 이상 계속 거주했거나 합산 10년 이상 거주한 만 24세 청년입니다.",
    support_content: "분기별 25만원(연 최대 100만원)을 해당 시군 지역화폐로 지급합니다. (예시 수치)",
    application_method: "경기민원24 홈페이지에서 온라인으로 신청합니다.",
    required_documents: ["주민등록초본(주소이력 포함)"],
    checklist: ["거주 이력이 요건을 충족하는지 초본으로 미리 확인하세요", "분기별 신청 기간을 놓치지 않도록 알림을 설정하세요"],
    faq: [],
    agency_name: "경기도 청년복지정책과",
    agency_url: null,
    income_condition: null,
    age_min: 24,
    age_max: 24,
    household_type: "무관",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "예시 데이터",
    source_updated_at: null,
    is_published: true,
  },
  {
    id: "b-incheon-birth-grant",
    slug: "incheon-birth-grant",
    title: "인천시 출산장려금 (예시)",
    summary: "인천에 거주하며 출산한 가정에 첫째부터 장려금을 지급합니다.",
    region_id: "r-incheon",
    category_id: "c-birth",
    eligibility: "출생일 기준 인천시에 주민등록을 두고 있는 가정이면 신청할 수 있습니다.",
    support_content: "첫째 100만원, 둘째 이상은 금액이 상향됩니다. (예시 수치이며 자치구별로 다를 수 있음)",
    application_method: "거주지 주민센터 방문 또는 정부24 온라인 신청이 가능합니다.",
    required_documents: ["출생신고 관련 서류", "주민등록등본", "통장 사본"],
    checklist: ["출생신고를 먼저 완료했는지 확인하세요", "거주 중인 구청/군청의 별도 조례 지원금도 함께 확인하세요"],
    faq: [],
    agency_name: "인천시 아동보육과",
    agency_url: null,
    income_condition: null,
    age_min: null,
    age_max: null,
    household_type: "무관",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "예시 데이터",
    source_updated_at: null,
    is_published: true,
  },
];
