import { Benefit, Category, Region } from "./types";

/**
 * Supabase가 아직 연결되지 않았을 때 사용하는 로컬 폴백 데이터입니다.
 * 내용은 supabase/seed.sql + supabase/seed_history.sql과 동일하게 유지하세요.
 * 제도는 예산 소진, 조례 개정 등으로 수시로 바뀔 수 있으니 화면에 노출하기 전에
 * agency_url의 공식 페이지에서 최신 기준을 다시 확인하세요.
 */

export const seedRegions: Region[] = [
  { id: "r-seoul", slug: "seoul", name: "서울특별시", level: "sido", parent_id: null },
  { id: "r-gyeonggi", slug: "gyeonggi", name: "경기도", level: "sido", parent_id: null },
  { id: "r-incheon", slug: "incheon", name: "인천광역시", level: "sido", parent_id: null },
  { id: "r-seoul-gangnam", slug: "seoul-gangnam", name: "강남구", level: "sigungu", parent_id: "r-seoul" },
  { id: "r-seoul-mapo", slug: "seoul-mapo", name: "마포구", level: "sigungu", parent_id: "r-seoul" },
  { id: "r-gyeonggi-suwon", slug: "gyeonggi-suwon", name: "수원시", level: "sigungu", parent_id: "r-gyeonggi" },
];

export const seedCategories: Category[] = [
  { id: "c-marriage", slug: "marriage", name: "결혼", description: "결혼 준비·신혼부부를 위한 지원 제도", sort_order: 1 },
  { id: "c-birth", slug: "birth", name: "출산·육아", description: "임신, 출산, 양육과 관련된 지원 제도", sort_order: 2 },
  { id: "c-youth", slug: "youth", name: "청년", description: "청년(만 19~39세 내외) 대상 지원 제도", sort_order: 3 },
  { id: "c-housing", slug: "housing", name: "주거", description: "전월세, 주택 구입 관련 지원 제도", sort_order: 4 },
];

export const seedBenefits: Benefit[] = [
  // ---------------------------------------------------------------------
  // 서울시 청년 월세 지원 (program_slug: seoul-youth-rent-support)
  // ---------------------------------------------------------------------
  {
    id: "b-seoul-youth-rent-support",
    slug: "seoul-youth-rent-support",
    title: "서울시 청년 월세 지원",
    summary: "서울에 거주하는 무주택 청년의 월세 부담을 줄여주는 서울시 지원 제도입니다.",
    region_id: "r-seoul",
    category_id: "c-housing",
    eligibility:
      "신청일 기준 서울시 주민등록을 둔 만 19~39세 무주택 청년으로, 부모와 따로 거주 중이며 가구 기준 중위소득 48% 초과 150% 이하여야 합니다. 임차보증금 8천만원 이하·월세 60만원 이하 주택(또는 보증금 환산액과 월세 합계 93만원 이하) 거주자만 해당하며, 국토부 청년월세 한시특별지원 수령자·공공임대주택 거주자·부모 소유 주택 임차인은 제외됩니다. 2026년부터는 1인가구 청년뿐 아니라 무자녀 신혼부부, 청년 한부모가족, 전세사기피해 청년까지 지원 대상이 확대되었습니다.",
    support_content:
      "월 최대 20만원씩 최장 12개월(생애 1회, 최대 240만원)을 지원합니다. 월세가 20만원보다 적으면 실제 월세만큼만 지급됩니다.",
    application_method:
      '서울주거포털(housing.seoul.go.kr) "청년월세지원" 메뉴에서 자가진단 후 온라인으로 접수합니다. 연중 상시가 아니라 별도 모집 공고 기간에만 신청할 수 있으니 공지사항을 미리 확인해야 합니다.',
    required_documents: ["임대차계약서", "월세 이체 내역", "가족관계증명서", "소득 증빙서류"],
    checklist: [
      "임대차계약서가 본인 명의인지 확인하세요",
      "부모 소유 주택에 거주 중이라면 대상이 아닙니다",
      "국토부 청년월세 한시특별지원을 이미 받았다면 중복 신청이 불가능합니다",
      "공공임대주택 거주자는 제외 대상입니다",
    ],
    faq: [
      { question: "월세가 20만원보다 적으면 어떻게 되나요?", answer: "실제 월세 금액만큼만 지원됩니다." },
      {
        question: "신청 기간이 정해져 있나요?",
        answer: "네, 상시 신청이 아니라 서울시가 공고하는 모집 기간에만 신청할 수 있습니다. 서울주거포털 공지사항을 확인하세요.",
      },
    ],
    agency_name: "서울시 청년정책담당관",
    agency_url: "https://housing.seoul.go.kr/",
    income_condition: "기준 중위소득 48% 초과 150% 이하",
    age_min: 19,
    age_max: 39,
    household_type: "1인가구",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: false,
    source_name: "서울주거포털 공고 및 언론 보도 기준 정리",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "seoul-youth-rent-support",
    fiscal_year: 2026,
    is_current: true,
  },
  {
    id: "b-seoul-youth-rent-support-2025",
    slug: "seoul-youth-rent-support-2025",
    title: "서울시 청년 월세 지원 (2025년)",
    summary: "2025년에 시행된 서울시 청년 월세 지원 제도입니다. 약 1만 5천명 규모로 8월부터 지원이 시작되었습니다.",
    region_id: "r-seoul",
    category_id: "c-housing",
    eligibility:
      "신청일 기준 서울시 주민등록을 둔 만 19~39세 무주택 1인가구 청년으로, 부모와 따로 거주 중이며 가구 기준 중위소득 48% 초과 150% 이하여야 했습니다. 임차보증금 8천만원 이하·월세 60만원 이하 주택(또는 보증금 환산액과 월세 합계 93만원 이하) 거주자만 해당했으며, 국토부 청년월세 한시특별지원 수령자·공공임대주택 거주자·부모 소유 주택 임차인은 제외됐습니다.",
    support_content: "월 최대 20만원씩 최장 12개월(최대 240만원)을 지원했습니다.",
    application_method: "서울주거포털에서 자가진단 후 온라인으로 접수했습니다. 2025년 모집은 이미 종료되었습니다.",
    required_documents: ["임대차계약서", "월세 이체 내역", "가족관계증명서", "소득 증빙서류"],
    checklist: ["이 페이지는 2025년도 종료된 모집 정보입니다", "최신 연도 신청 조건은 현재 페이지를 확인하세요"],
    faq: [],
    agency_name: "서울시 청년정책담당관",
    agency_url: "https://housing.seoul.go.kr/",
    income_condition: "기준 중위소득 48% 초과 150% 이하",
    age_min: 19,
    age_max: 39,
    household_type: "1인가구",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: false,
    source_name: "서울주거포털 공고 및 언론 보도 기준 정리 (과거 연도 기록)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "seoul-youth-rent-support",
    fiscal_year: 2025,
    is_current: false,
  },
  {
    id: "b-seoul-youth-rent-support-2024",
    slug: "seoul-youth-rent-support-2024",
    title: "서울시 청년 월세 지원 (2024년)",
    summary: "2024년에 시행된 서울시 청년 월세 지원 제도입니다.",
    region_id: "r-seoul",
    category_id: "c-housing",
    eligibility:
      "신청일 기준 서울시 주민등록을 둔 만 19~39세 무주택 1인가구 청년으로, 부모와 따로 거주 중이며 가구 기준 중위소득 48% 초과 150% 이하여야 했습니다. 임차보증금 8천만원 이하·월세 60만원 이하 주택(또는 보증금 환산액과 월세 합계 93만원 이하) 거주자만 해당했으며, 국토부 청년월세 한시특별지원 수령자·공공임대주택 거주자·부모 소유 주택 임차인은 제외됐습니다.",
    support_content: "월 최대 20만원씩 최장 12개월(최대 240만원)을 지원했습니다.",
    application_method: "서울주거포털에서 자가진단 후 온라인으로 접수했습니다. 2024년 모집은 이미 종료되었습니다.",
    required_documents: ["임대차계약서", "월세 이체 내역", "가족관계증명서", "소득 증빙서류"],
    checklist: ["이 페이지는 2024년도 종료된 모집 정보입니다", "최신 연도 신청 조건은 현재 페이지를 확인하세요"],
    faq: [],
    agency_name: "서울시 청년정책담당관",
    agency_url: "https://housing.seoul.go.kr/",
    income_condition: "기준 중위소득 48% 초과 150% 이하",
    age_min: 19,
    age_max: 39,
    household_type: "1인가구",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: false,
    source_name: "서울주거포털 공고 및 언론 보도 기준 정리 (과거 연도 기록)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "seoul-youth-rent-support",
    fiscal_year: 2024,
    is_current: false,
  },
  {
    id: "b-seoul-youth-rent-support-2023",
    slug: "seoul-youth-rent-support-2023",
    title: "서울시 청년 월세 지원 (2023년)",
    summary: "2023년에 시행된 서울시 청년 월세 지원 제도입니다.",
    region_id: "r-seoul",
    category_id: "c-housing",
    eligibility:
      "신청일 기준 서울시 주민등록을 둔 만 19~39세 무주택 1인가구 청년으로, 부모와 따로 거주 중이며 가구 기준 중위소득 48% 초과 150% 이하여야 했습니다. 임차보증금 8천만원 이하·월세 60만원 이하 주택(또는 보증금 환산액과 월세 합계 93만원 이하) 거주자만 해당했으며, 국토부 청년월세 한시특별지원 수령자·공공임대주택 거주자·부모 소유 주택 임차인은 제외됐습니다.",
    support_content: "월 최대 20만원씩 최장 12개월(최대 240만원)을 지원했습니다.",
    application_method: "서울주거포털에서 자가진단 후 온라인으로 접수했습니다. 2023년 모집은 이미 종료되었습니다.",
    required_documents: ["임대차계약서", "월세 이체 내역", "가족관계증명서", "소득 증빙서류"],
    checklist: ["이 페이지는 2023년도 종료된 모집 정보입니다", "최신 연도 신청 조건은 현재 페이지를 확인하세요"],
    faq: [],
    agency_name: "서울시 청년정책담당관",
    agency_url: "https://housing.seoul.go.kr/",
    income_condition: "기준 중위소득 48% 초과 150% 이하",
    age_min: 19,
    age_max: 39,
    household_type: "1인가구",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: false,
    source_name: "서울주거포털 공고 및 언론 보도 기준 정리 (과거 연도 기록)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "seoul-youth-rent-support",
    fiscal_year: 2023,
    is_current: false,
  },
  {
    id: "b-seoul-youth-rent-support-2022",
    slug: "seoul-youth-rent-support-2022",
    title: "서울시 청년 월세 지원 (2022년)",
    summary: "서울시 청년 월세 지원 사업이 본격적으로 시행된 첫 해입니다. 2022년 11월부터 월세 지원이 시작되었습니다.",
    region_id: "r-seoul",
    category_id: "c-housing",
    eligibility:
      "신청일 기준 서울시 주민등록을 둔 만 19~39세 무주택 1인가구 청년으로, 부모와 따로 거주 중이며 가구 기준 중위소득 48% 초과 150% 이하여야 했습니다. 임차보증금 8천만원 이하·월세 60만원 이하 주택 거주자만 해당했습니다.",
    support_content: "2022년 11월부터 월 최대 20만원씩 12개월분(최대 240만원)을 지원했습니다.",
    application_method: "서울주거포털에서 자가진단 후 온라인으로 접수했습니다. 2022년 모집은 이미 종료되었습니다.",
    required_documents: ["임대차계약서", "월세 이체 내역", "가족관계증명서", "소득 증빙서류"],
    checklist: ["이 페이지는 2022년도 종료된 모집 정보입니다", "최신 연도 신청 조건은 현재 페이지를 확인하세요"],
    faq: [],
    agency_name: "서울시 청년정책담당관",
    agency_url: "https://housing.seoul.go.kr/",
    income_condition: "기준 중위소득 48% 초과 150% 이하",
    age_min: 19,
    age_max: 39,
    household_type: "1인가구",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: false,
    source_name: "서울주거포털 공고 및 언론 보도 기준 정리 (과거 연도 기록)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "seoul-youth-rent-support",
    fiscal_year: 2022,
    is_current: false,
  },

  // ---------------------------------------------------------------------
  // 서울시 신혼부부 임차보증금 이자지원 (program_slug: seoul-newlywed-loan-interest)
  // ---------------------------------------------------------------------
  {
    id: "b-seoul-newlywed-loan-interest",
    slug: "seoul-newlywed-loan-interest",
    title: "서울시 신혼부부 임차보증금 이자지원",
    summary: "전세자금 대출을 받은 서울 거주 신혼(예비)부부에게 이자를 지원하는 제도입니다.",
    region_id: "r-seoul",
    category_id: "c-marriage",
    eligibility:
      "대출신청일 기준 혼인신고 7년 이내이거나 6개월 이내 결혼 예정인 신혼(예비)부부로, 부부합산 연소득 1억 3천만원 이하이며 본인과 배우자 모두 무주택자여야 합니다. 서울시민이거나 대출 후 1개월 이내 서울로 전입할 예정이어야 합니다.",
    support_content:
      "임차보증금 7억원 이하 주택(주거용 오피스텔·노인복지주택 포함)에 대해 보증금의 90% 이내, 최대 3억원까지 대출 이자를 지원합니다. 부부 1쌍당 생애 최초 1회 지원되며, 조건 충족 시 연장을 통해 최장 10년까지 이용할 수 있습니다.",
    application_method: "서울주거포털에서 대상자 여부를 먼저 확인한 뒤, 협약은행을 방문해 대출을 신청합니다.",
    required_documents: ["혼인관계증명서(또는 예비부부 증빙 서류)", "임대차계약서", "부부합산 소득 증빙서류", "무주택 확인서류"],
    checklist: [
      "부부합산 연소득이 1억 3천만원을 넘지 않는지 확인하세요",
      "본인과 배우자 모두 무주택자여야 합니다",
      "임차보증금이 7억원을 넘지 않는 주택인지 확인하세요",
      "생애 1회만 지원되니 이전에 받은 적이 있는지 확인하세요",
    ],
    faq: [
      {
        question: "결혼 준비 중인데도 신청할 수 있나요?",
        answer: "대출신청일로부터 6개월 이내 결혼식 예정인 예비부부도 신청할 수 있습니다.",
      },
    ],
    agency_name: "서울시 주택정책과",
    agency_url: "https://housing.seoul.go.kr/site/main/content/sh01_0400800",
    income_condition: "부부합산 연소득 1억 3천만원 이하",
    age_min: null,
    age_max: null,
    household_type: "신혼부부",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "서울주거포털 공고 및 언론 보도 기준 정리",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "seoul-newlywed-loan-interest",
    fiscal_year: 2026,
    is_current: true,
  },
  {
    id: "b-seoul-newlywed-loan-interest-2025",
    slug: "seoul-newlywed-loan-interest-2025",
    title: "서울시 신혼부부 임차보증금 이자지원 (2025년)",
    summary: "2025년 기준 서울시 신혼부부 임차보증금 이자지원 제도입니다.",
    region_id: "r-seoul",
    category_id: "c-marriage",
    eligibility:
      "대출신청일 기준 혼인신고 7년 이내이거나 6개월 이내 결혼 예정인 신혼(예비)부부로, 부부합산 연소득 1억 3천만원 이하이며 본인과 배우자 모두 무주택자여야 했습니다.",
    support_content: "임차보증금 7억원 이하 주택에 대해 보증금의 90% 이내, 최대 3억원까지 대출 이자를 지원했습니다.",
    application_method: "서울주거포털에서 대상자 여부를 확인한 뒤 협약은행에서 대출을 신청했습니다.",
    required_documents: ["혼인관계증명서(또는 예비부부 증빙 서류)", "임대차계약서", "부부합산 소득 증빙서류", "무주택 확인서류"],
    checklist: ["이 페이지는 2025년도 기록입니다", "최신 연도 조건은 현재 페이지를 확인하세요"],
    faq: [],
    agency_name: "서울시 주택정책과",
    agency_url: "https://housing.seoul.go.kr/site/main/content/sh01_0400800",
    income_condition: "부부합산 연소득 1억 3천만원 이하",
    age_min: null,
    age_max: null,
    household_type: "신혼부부",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "서울주거포털 공고 및 언론 보도 기준 정리 (과거 연도 기록)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "seoul-newlywed-loan-interest",
    fiscal_year: 2025,
    is_current: false,
  },
  {
    id: "b-seoul-newlywed-loan-interest-2024",
    slug: "seoul-newlywed-loan-interest-2024",
    title: "서울시 신혼부부 임차보증금 이자지원 (2024년)",
    summary: "2024년 기준 서울시 신혼부부 임차보증금 이자지원 제도입니다. 전년도 5월 확대된 3억원 한도가 그대로 유지되었습니다.",
    region_id: "r-seoul",
    category_id: "c-marriage",
    eligibility:
      "대출신청일 기준 혼인신고 7년 이내이거나 6개월 이내 결혼 예정인 신혼(예비)부부로, 부부합산 연소득 1억 3천만원 이하이며 본인과 배우자 모두 무주택자여야 했습니다.",
    support_content: "임차보증금 7억원 이하 주택에 대해 보증금의 90% 이내, 최대 3억원까지 대출 이자를 지원했습니다.",
    application_method: "서울주거포털에서 대상자 여부를 확인한 뒤 협약은행에서 대출을 신청했습니다.",
    required_documents: ["혼인관계증명서(또는 예비부부 증빙 서류)", "임대차계약서", "부부합산 소득 증빙서류", "무주택 확인서류"],
    checklist: ["이 페이지는 2024년도 기록입니다", "최신 연도 조건은 현재 페이지를 확인하세요"],
    faq: [],
    agency_name: "서울시 주택정책과",
    agency_url: "https://housing.seoul.go.kr/site/main/content/sh01_0400800",
    income_condition: "부부합산 연소득 1억 3천만원 이하",
    age_min: null,
    age_max: null,
    household_type: "신혼부부",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "서울주거포털 공고 및 언론 보도 기준 정리 (과거 연도 기록, 소득기준 정확한 변경일은 미확인)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "seoul-newlywed-loan-interest",
    fiscal_year: 2024,
    is_current: false,
  },
  {
    id: "b-seoul-newlywed-loan-interest-2023",
    slug: "seoul-newlywed-loan-interest-2023",
    title: "서울시 신혼부부 임차보증금 이자지원 (2023년)",
    summary: "2023년 5월 2일 대출한도가 2억원에서 3억원으로 상향된 해입니다.",
    region_id: "r-seoul",
    category_id: "c-marriage",
    eligibility: "대출신청일 기준 혼인신고 7년 이내이거나 6개월 이내 결혼 예정인 신혼(예비)부부가 대상이었습니다.",
    support_content:
      "2023년 5월 1일까지는 대출한도가 최대 2억원이었으나, 5월 2일 신청 건부터 임차보증금의 90% 이내, 최대 3억원으로 상향되었습니다.",
    application_method: "서울주거포털에서 대상자 여부를 확인한 뒤 협약은행에서 대출을 신청했습니다.",
    required_documents: ["혼인관계증명서(또는 예비부부 증빙 서류)", "임대차계약서", "부부합산 소득 증빙서류", "무주택 확인서류"],
    checklist: ["이 페이지는 2023년도 기록입니다", "5월 2일 전후로 대출한도가 달랐던 해입니다", "최신 연도 조건은 현재 페이지를 확인하세요"],
    faq: [],
    agency_name: "서울시 주택정책과",
    agency_url: "https://housing.seoul.go.kr/site/main/content/sh01_0400800",
    income_condition: "2023년 5월 이전 부부합산 연소득 9,700만원 이하 → 이후 완화",
    age_min: null,
    age_max: null,
    household_type: "신혼부부",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "서울주거포털 공고 및 언론 보도 기준 정리 (과거 연도 기록)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "seoul-newlywed-loan-interest",
    fiscal_year: 2023,
    is_current: false,
  },
  {
    id: "b-seoul-newlywed-loan-interest-2022",
    slug: "seoul-newlywed-loan-interest-2022",
    title: "서울시 신혼부부 임차보증금 이자지원 (2022년)",
    summary: "2022년 기준 서울시 신혼부부 임차보증금 이자지원 제도입니다. 이 시기 대출한도는 최대 2억원이었습니다.",
    region_id: "r-seoul",
    category_id: "c-marriage",
    eligibility:
      "대출신청일 기준 혼인신고 7년 이내이거나 6개월 이내 결혼 예정인 신혼(예비)부부로, 부부합산 연소득 9,700만원 이하이며 본인과 배우자 모두 무주택자여야 했습니다.",
    support_content: "임차보증금 7억원 이하 주택에 대해 보증금의 90% 이내, 최대 2억원까지 대출 이자를 지원했습니다.",
    application_method: "서울주거포털에서 대상자 여부를 확인한 뒤 협약은행에서 대출을 신청했습니다.",
    required_documents: ["혼인관계증명서(또는 예비부부 증빙 서류)", "임대차계약서", "부부합산 소득 증빙서류", "무주택 확인서류"],
    checklist: ["이 페이지는 2022년도 기록입니다", "대출한도가 현재보다 낮았던 해입니다", "최신 연도 조건은 현재 페이지를 확인하세요"],
    faq: [],
    agency_name: "서울시 주택정책과",
    agency_url: "https://housing.seoul.go.kr/site/main/content/sh01_0400800",
    income_condition: "부부합산 연소득 9,700만원 이하",
    age_min: null,
    age_max: null,
    household_type: "신혼부부",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "서울주거포털 공고 및 언론 보도 기준 정리 (과거 연도 기록)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "seoul-newlywed-loan-interest",
    fiscal_year: 2022,
    is_current: false,
  },

  // ---------------------------------------------------------------------
  // 경기도 청년기본소득 (program_slug: gyeonggi-basic-income-youth)
  // ---------------------------------------------------------------------
  {
    id: "b-gyeonggi-basic-income-youth",
    slug: "gyeonggi-basic-income-youth",
    title: "경기도 청년기본소득",
    summary: "경기도에 일정 기간 거주한 만 24세 청년에게 분기별로 지역화폐를 지급하는 제도입니다.",
    region_id: "r-gyeonggi",
    category_id: "c-youth",
    eligibility:
      "신청일 기준 경기도에 주민등록을 둔 만 24세 청년 중 최근 3년 이상 계속 거주했거나 합산 10년 이상 거주한 경우 신청할 수 있습니다. 다만 성남시는 관련 조례가 폐지되었고 고양시는 예산이 편성되지 않아 두 지역은 신청 대상에서 제외됩니다.",
    support_content: "분기별 25만원씩 연 최대 100만원을 지역화폐로 지급합니다.",
    application_method:
      '경기청년포털과 연계된 "잡아바 어플라이"에서 온라인으로 신청합니다. 로그인 후 "청년기본소득" 메뉴에서 신청서를 작성하며, 마이데이터 서비스에 동의하면 주민등록초본이 별도 발급 없이 자동 제출됩니다. 신청 기간은 분기마다 다르게 공지됩니다.',
    required_documents: ["신분증(본인 확인용)", "주민등록초본(마이데이터 미동의 시)"],
    checklist: [
      "거주 중인 시군이 성남시·고양시 등 제외 지역이 아닌지 확인하세요",
      "해당 분기에 만 24세인지 확인하세요",
      "최근 3년 계속 거주 또는 합산 10년 거주 요건 중 하나를 충족해야 합니다",
      "분기별로 각각 신청해야 하며 놓친 분기는 지급되지 않습니다",
    ],
    faq: [
      {
        question: "한 번 신청하면 4번 다 받을 수 있나요?",
        answer: "아니요, 분기마다 별도로 신청해야 하며 신청하지 않은 분기는 지급되지 않습니다.",
      },
    ],
    agency_name: "경기도 청년복지정책과",
    agency_url: "https://youth.gg.go.kr/",
    income_condition: null,
    age_min: 24,
    age_max: 24,
    household_type: "무관",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "경기청년포털 공고 기준 정리",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "gyeonggi-basic-income-youth",
    fiscal_year: 2026,
    is_current: true,
  },
  {
    id: "b-gyeonggi-basic-income-youth-2025",
    slug: "gyeonggi-basic-income-youth-2025",
    title: "경기도 청년기본소득 (2025년)",
    summary: "2025년 기준 경기도 청년기본소득 제도입니다. 이 해부터 성남시와 고양시가 지급 대상에서 제외되었습니다.",
    region_id: "r-gyeonggi",
    category_id: "c-youth",
    eligibility:
      "신청일 기준 경기도에 주민등록을 둔 만 24세 청년 중 최근 3년 이상 계속 거주했거나 합산 10년 이상 거주한 경우 신청할 수 있었습니다. 2025년에는 성남시와 고양시가 신청 대상에서 제외되었습니다.",
    support_content: "분기별 25만원씩 연 최대 100만원을 지역화폐로 지급했습니다.",
    application_method: '경기청년포털과 연계된 "잡아바 어플라이"에서 온라인으로 신청했습니다.',
    required_documents: ["신분증(본인 확인용)", "주민등록초본(마이데이터 미동의 시)"],
    checklist: ["이 페이지는 2025년도 기록입니다", "최신 연도 제외 지역은 현재 페이지를 확인하세요"],
    faq: [],
    agency_name: "경기도 청년복지정책과",
    agency_url: "https://youth.gg.go.kr/",
    income_condition: null,
    age_min: 24,
    age_max: 24,
    household_type: "무관",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "경기청년포털 공고 및 언론 보도 기준 정리 (과거 연도 기록)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "gyeonggi-basic-income-youth",
    fiscal_year: 2025,
    is_current: false,
  },
  {
    id: "b-gyeonggi-basic-income-youth-2024",
    slug: "gyeonggi-basic-income-youth-2024",
    title: "경기도 청년기본소득 (2024년)",
    summary: "2024년 기준 경기도 청년기본소득 제도입니다. 성남시(조례 폐지)와 의정부시(예산 미편성)가 지급 대상에서 제외되었습니다.",
    region_id: "r-gyeonggi",
    category_id: "c-youth",
    eligibility:
      "신청일 기준 경기도에 주민등록을 둔 만 24세 청년 중 최근 3년 이상 계속 거주했거나 합산 10년 이상 거주한 경우 신청할 수 있었습니다. 2024년에는 성남시(조례 폐지)와 의정부시(예산 미편성)가 신청 대상에서 제외되었습니다.",
    support_content: "분기별 25만원씩 연 최대 100만원을 지역화폐로 지급했습니다.",
    application_method: '경기청년포털과 연계된 "잡아바 어플라이"에서 온라인으로 신청했습니다.',
    required_documents: ["신분증(본인 확인용)", "주민등록초본(마이데이터 미동의 시)"],
    checklist: ["이 페이지는 2024년도 기록입니다", "최신 연도 제외 지역은 현재 페이지를 확인하세요"],
    faq: [],
    agency_name: "경기도 청년복지정책과",
    agency_url: "https://youth.gg.go.kr/",
    income_condition: null,
    age_min: 24,
    age_max: 24,
    household_type: "무관",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "경기청년포털 공고 및 언론 보도 기준 정리 (과거 연도 기록)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "gyeonggi-basic-income-youth",
    fiscal_year: 2024,
    is_current: false,
  },
  {
    id: "b-gyeonggi-basic-income-youth-2023",
    slug: "gyeonggi-basic-income-youth-2023",
    title: "경기도 청년기본소득 (2023년)",
    summary: "2023년 기준 경기도 청년기본소득 제도입니다.",
    region_id: "r-gyeonggi",
    category_id: "c-youth",
    eligibility:
      "신청일 기준 경기도에 주민등록을 둔 만 24세 청년 중 최근 3년 이상 계속 거주했거나 합산 10년 이상 거주한 경우 신청할 수 있었습니다. 이번 조사에서는 이 해의 별도 제외 지자체 정보를 확인하지 못했습니다. 정확한 내용은 경기도청에 문의하세요.",
    support_content: "분기별 25만원씩 연 최대 100만원을 지역화폐로 지급했습니다.",
    application_method: "경기청년포털과 연계된 신청 채널에서 온라인으로 신청했습니다.",
    required_documents: ["신분증(본인 확인용)", "주민등록초본(마이데이터 미동의 시)"],
    checklist: ["이 페이지는 2023년도 기록입니다", "제외 지역 정보는 이번 조사에서 확인되지 않았습니다"],
    faq: [],
    agency_name: "경기도 청년복지정책과",
    agency_url: "https://youth.gg.go.kr/",
    income_condition: null,
    age_min: 24,
    age_max: 24,
    household_type: "무관",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "경기청년포털 공고 및 언론 보도 기준 정리 (과거 연도 기록, 제외지역 정보 미확인)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "gyeonggi-basic-income-youth",
    fiscal_year: 2023,
    is_current: false,
  },
  {
    id: "b-gyeonggi-basic-income-youth-2022",
    slug: "gyeonggi-basic-income-youth-2022",
    title: "경기도 청년기본소득 (2022년)",
    summary: "2022년 기준 경기도 청년기본소득 제도입니다.",
    region_id: "r-gyeonggi",
    category_id: "c-youth",
    eligibility:
      "신청일 기준 경기도에 주민등록을 둔 만 24세 청년 중 최근 3년 이상 계속 거주했거나 합산 10년 이상 거주한 경우 신청할 수 있었습니다. 이번 조사에서는 이 해의 별도 제외 지자체 정보를 확인하지 못했습니다. 정확한 내용은 경기도청에 문의하세요.",
    support_content: "분기별 25만원씩 연 최대 100만원을 지역화폐로 지급했습니다.",
    application_method: "경기청년포털과 연계된 신청 채널에서 온라인으로 신청했습니다.",
    required_documents: ["신분증(본인 확인용)", "주민등록초본(마이데이터 미동의 시)"],
    checklist: ["이 페이지는 2022년도 기록입니다", "제외 지역 정보는 이번 조사에서 확인되지 않았습니다"],
    faq: [],
    agency_name: "경기도 청년복지정책과",
    agency_url: "https://youth.gg.go.kr/",
    income_condition: null,
    age_min: 24,
    age_max: 24,
    household_type: "무관",
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "경기청년포털 공고 및 언론 보도 기준 정리 (과거 연도 기록, 제외지역 정보 미확인)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "gyeonggi-basic-income-youth",
    fiscal_year: 2022,
    is_current: false,
  },

  // ---------------------------------------------------------------------
  // 인천시 맘편한 산후조리비 지원 (program_slug: incheon-postpartum-care-support)
  // 2025년 1월 1일 출산자부터 신규 시행된 사업이라 2025년 기록만 존재합니다.
  // ---------------------------------------------------------------------
  {
    id: "b-incheon-postpartum-care-support",
    slug: "incheon-postpartum-care-support",
    title: "인천시 맘편한 산후조리비 지원",
    summary: "인천에 거주하는 취약계층 산모에게 산후조리비를 지역화폐로 지원하는 제도입니다.",
    region_id: "r-incheon",
    category_id: "c-birth",
    eligibility:
      "신청일 기준 인천시에 1년 이상 계속 주민등록을 두고 거주 중인 취약계층 산모(기초생활수급자, 차상위계층, 한부모가족, 장애인 등)가 대상입니다. 중앙육아종합지원센터의 부모교육(e-러닝) 이수가 필수 조건입니다.",
    support_content:
      "산모 1인당 150만원을 인천e음 지역화폐 포인트로 지급합니다. 이는 인천시 통합 지원이며, 거주 중인 자치구에 따라 별도의 추가 산후조리비 지원사업이 있을 수 있습니다.",
    application_method: "임신 32주부터 출산 후 90일 이내에 거주지 관할 보건소를 통해 신청합니다.",
    required_documents: [
      "산모수첩 또는 임신확인서(임신 중 신청 시)",
      "출생신고 관련 서류(출산 후 신청 시)",
      "취약계층 증빙서류",
      "부모교육 이수 확인서",
    ],
    checklist: [
      "신청일 기준 인천시에 1년 이상 계속 거주했는지 확인하세요",
      "중앙육아종합지원센터 부모교육을 미리 이수해두세요",
      "임신 32주~출산 후 90일 이내 신청 기간을 놓치지 마세요",
      "거주 중인 구청 보건소의 추가 자체 지원사업도 함께 확인하세요",
    ],
    faq: [
      {
        question: "취약계층이 아니어도 받을 수 있나요?",
        answer:
          "이 통합 지원은 기초생활수급자, 차상위계층, 한부모가족, 장애인 등 취약계층 산모를 대상으로 합니다. 해당하지 않는다면 거주 중인 자치구의 별도 산후조리비 지원사업을 확인해보세요.",
      },
    ],
    agency_name: "인천시 여성가족과 / 관할 보건소",
    agency_url: "https://www.incheon.go.kr/welfare/WE020355",
    income_condition: "기초생활수급자·차상위계층 등 취약계층 기준",
    age_min: null,
    age_max: null,
    household_type: null,
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "인천광역시청 공식 홈페이지 기준 정리",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "incheon-postpartum-care-support",
    fiscal_year: 2026,
    is_current: true,
  },
  {
    id: "b-incheon-postpartum-care-support-2025",
    slug: "incheon-postpartum-care-support-2025",
    title: "인천시 맘편한 산후조리비 지원 (2025년)",
    summary: "2025년 1월 1일 출산자부터 처음 시행된 인천시 맘편한 산후조리비 지원 제도입니다.",
    region_id: "r-incheon",
    category_id: "c-birth",
    eligibility:
      "신청일 기준 인천시에 1년 이상 계속 주민등록을 두고 거주 중인 취약계층 산모(기초생활수급자, 차상위계층, 한부모가족, 장애인 등)가 대상이었습니다. 중앙육아종합지원센터의 부모교육(e-러닝) 이수가 필수 조건이었습니다.",
    support_content: "산모 1인당 150만원을 인천e음 지역화폐 포인트로 지급했습니다. 2025년 1월 1일 출산자부터 적용된 신규 사업입니다.",
    application_method: "임신 32주부터 출산 후 90일 이내에 거주지 관할 보건소를 통해 신청했습니다.",
    required_documents: [
      "산모수첩 또는 임신확인서(임신 중 신청 시)",
      "출생신고 관련 서류(출산 후 신청 시)",
      "취약계층 증빙서류",
      "부모교육 이수 확인서",
    ],
    checklist: ["이 제도는 2025년에 처음 시행되어 그 이전 연도 기록은 없습니다", "최신 연도 조건은 현재 페이지를 확인하세요"],
    faq: [],
    agency_name: "인천시 여성가족과 / 관할 보건소",
    agency_url: "https://www.incheon.go.kr/welfare/WE020355",
    income_condition: "기초생활수급자·차상위계층 등 취약계층 기준",
    age_min: null,
    age_max: null,
    household_type: null,
    application_start_date: null,
    application_end_date: null,
    is_ongoing: true,
    source_name: "인천광역시청 공식 홈페이지 기준 정리 (과거 연도 기록)",
    source_updated_at: "2026-09-21",
    is_published: true,
    program_slug: "incheon-postpartum-care-support",
    fiscal_year: 2025,
    is_current: false,
  },
];
